# Generated by Django 6.1 on 2026-10-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_bike_editorial_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='image_name',
            field=models.CharField(blank=True, help_text='Optional existing file name in the static folder.', max_length=120),
        ),
        migrations.AlterField(
            model_name='bike',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='booking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
