# Generated by Django 6.1 on 2026-10-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_v4s_naked_sports_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='cooling',
            field=models.CharField(blank=True, help_text='For example, liquid-cooled.', max_length=80),
        ),
        migrations.AddField(
            model_name='bike',
            name='engine_configuration',
            field=models.CharField(blank=True, help_text='For example, parallel twin or V4.', max_length=80),
        ),
        migrations.AddField(
            model_name='bike',
            name='front_brake',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='bike',
            name='front_suspension',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='bike',
            name='fuel_capacity_l',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Fuel capacity (L)'),
        ),
        migrations.AddField(
            model_name='bike',
            name='fuel_system',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bike',
            name='kerb_weight_kg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Kerb weight (kg)'),
        ),
        migrations.AddField(
            model_name='bike',
            name='model_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Enter the model/manufacturing year when confirmed.', null=True, verbose_name='Model year'),
        ),
        migrations.AddField(
            model_name='bike',
            name='rear_brake',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='bike',
            name='rear_suspension',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='bike',
            name='safety_features',
            field=models.CharField(blank=True, help_text='List only confirmed rider-assistance and safety equipment.', max_length=240),
        ),
        migrations.AddField(
            model_name='bike',
            name='seat_height_mm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Seat height (mm)'),
        ),
        migrations.AddField(
            model_name='bike',
            name='transmission',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
