# Generated by Django 6.1 on 2026-10-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_v4s_confirmed_performance_figures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandcontent',
            name='engineering_story',
            field=models.TextField(default='Precision engineering starts with a clear purpose. We consider how a motorcycle looks, feels and responds, then pay attention to the details that bring the whole experience together—from its stance and riding position to its power and everyday usability. Our aim is to balance expressive design with confidence-inspiring performance, and to share specifications clearly so riders can choose with confidence.'),
        ),
        migrations.AlterField(
            model_name='brandcontent',
            name='heritage_intro',
            field=models.CharField(default='An Indian point of view, a clear sense of purpose, and a road still unfolding.', max_length=240),
        ),
        migrations.AlterField(
            model_name='brandcontent',
            name='heritage_story',
            field=models.TextField(default='Every road asks something different of a motorcycle. From the close rhythm of city traffic to the open stretch beyond familiar places, riders look for confidence, character and a machine that feels their own.\n\nDAVIDPUTTRA is shaped around that idea. Our Indian perspective informs how we think about design and the riding experience: expressive machines, purposeful performance and a closer connection to the people who ride them. We keep looking forward while staying grounded in the spirit of the road.'),
        ),
        migrations.AlterField(
            model_name='brandcontent',
            name='satisfaction_story',
            field=models.TextField(default='Customer care should feel as personal as the ride. We want it to be straightforward to explore the lineup, speak with our team, book a test ride and find service support. Clear information, attentive follow-up and a willingness to listen are the foundations of a better relationship with every rider.'),
        ),
    ]
