# Generated by Django 6.1 on 2026-10-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_expand_default_heritage_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandcontent',
            name='founders_names',
            field=models.CharField(default='Suvro, Roumo & Pramit', max_length=180),
        ),
        migrations.AddField(
            model_name='brandcontent',
            name='founders_story',
            field=models.TextField(default='DAVIDPUTTRA is a West Bengal-based motorcycle brand founded by three friends: Suvro, Roumo and Pramit. All three are passionate riders. Their shared love of motorcycles inspired them to create a brand shaped by an Indian point of view and a close connection to riders.'),
        ),
        migrations.AddField(
            model_name='brandcontent',
            name='founders_title',
            field=models.CharField(default='Three friends. One shared passion for riding.', max_length=180),
        ),
        migrations.AddField(
            model_name='brandcontent',
            name='origin_label',
            field=models.CharField(default='WEST BENGAL, INDIA', max_length=120),
        ),
    ]
