# Generated by Django 6.1 on 2026-10-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_correct_founders_heritage_copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerCoverageCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, unique=True)),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='State / territory')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='City-centre map pin; use a branch pin in Showroom & Service Locations for exact directions.', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('showroom_available', models.BooleanField(default=True)),
                ('service_center_available', models.BooleanField(default=True)),
                ('availability_note', models.CharField(blank=True, help_text='Optional note shown beside this city.', max_length=240)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'City coverage',
                'verbose_name_plural': 'City coverage',
                'ordering': ('city',),
            },
        ),
        migrations.AddField(
            model_name='bike',
            name='is_rentable',
            field=models.BooleanField(default=False, help_text='Show the rental option only after rates, availability and terms are configured.'),
        ),
        migrations.AddField(
            model_name='bike',
            name='rental_daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rental rate per day'),
        ),
        migrations.AddField(
            model_name='bike',
            name='rental_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rental security deposit'),
        ),
        migrations.AddField(
            model_name='bike',
            name='rental_max_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Maximum rental days'),
        ),
        migrations.AddField(
            model_name='bike',
            name='rental_min_days',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Minimum rental days'),
        ),
        migrations.AddField(
            model_name='bike',
            name='rental_terms',
            field=models.TextField(blank=True, help_text='Rental terms displayed before checkout.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='amount_paise',
            field=models.PositiveBigIntegerField(default=0, help_text='Amount charged through Razorpay in currency subunits.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('test_ride', 'Test ride'), ('rental', 'Rental')], default='test_ride', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='rental_daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate snapshot when this rental was booked.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='rental_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='rental_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deposit snapshot when this rental was booked.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_date',
            field=models.DateField(blank=True, help_text='Rental return date; end date is exclusive for duration calculation.', null=True),
        ),
    ]
