# Generated by Django 6.1 on 2026-10-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_seed_confirmed_coverage_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='rental_units',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of this model available to rent at the selected location.', verbose_name='Rental fleet quantity'),
        ),
    ]
