# Generated by Django 6.1 on 2026-10-09 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_seed_coverage_cities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brandcontent',
            name='home_cta_title',
            field=models.CharField(default='FEEL THE DIFFERENCE.', max_length=120),
        ),
        migrations.AddField(
            model_name='brandcontent',
            name='home_description',
            field=models.TextField(default='Motorcycles for riders who demand character, confident performance and the freedom to take the longer road. Designed with Indian spirit. Made for every journey ahead.'),
        ),
        migrations.AddField(
            model_name='brandcontent',
            name='home_promise_description',
            field=models.TextField(default='Thoughtful design and responsive support are part of the ride. Meet the people and principles behind DAVIDPUTTRA.'),
        ),
        migrations.AddField(
            model_name='brandcontent',
            name='home_promise_title',
            field=models.CharField(default='PRECISION ENGINEERING. CARE THAT GOES FURTHER.', max_length=180),
        ),
        migrations.AddField(
            model_name='brandcontent',
            name='home_tagline',
            field=models.CharField(default='DIL SE INDIAN', max_length=120),
        ),
        migrations.AddField(
            model_name='brandcontent',
            name='home_title_line_1',
            field=models.CharField(default='BUILT FOR', max_length=80),
        ),
        migrations.AddField(
            model_name='brandcontent',
            name='home_title_line_2',
            field=models.CharField(default='LEGENDS', max_length=80),
        ),
        migrations.AddField(
            model_name='brandcontent',
            name='home_title_line_3',
            field=models.CharField(default='ONLY.', max_length=80),
        ),
        migrations.CreateModel(
            name='ChatbotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(db_index=True, max_length=64)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('assistant', 'Assistant')], max_length=12)),
                ('message', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chatbot message',
                'verbose_name_plural': 'Chatbot messages',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=255)),
                ('visited_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page visit',
                'verbose_name_plural': 'Page visits',
                'ordering': ('-visited_at',),
            },
        ),
    ]
